server:
  port: 8081

spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/mobile_ms
      username: postgres
      password: root
      
  jpa:
    generate-ddl: true
    show-sql: true
    
vendorName: paytm4    